### ISSUE TITLE
Big query connector

### ISSUE THREAD

**Issue by hassanjahmed** [GoogleCloudPlatform/pubsub#112]
I made [this](https://github.com/bomboradata/pubsub-to-bigquery) dataflow pipeline that will connect Pub/Sub to Big query. Any ideas where would be the right place to commit this.

**Comment by kamalaboulhosn** [comment]
@hassanjahmed, thank you for your interest and contributions to Google Cloud Pub/Sub and BigQuery. I would recommend hosting the connector somewhere like GitHub where others who are interested can easily access it and possibly make improvements to it that you can review.
