### ISSUE TITLE
Google Pub-Sub Gives Permissions Denied

### ISSUE THREAD

**Issue by cloudbetaguy** [GoogleCloudPlatform/pubsub#142]
Trying out the Java Example of Publishing to Google Pub/Sub. Keep Getting Permission Denied. I am using a JSON Key for a Service Account which has Admin Access as well as Publisher Access to the Pub/Sub.
I have set Environment Variable "GOOGLE_APPLICATION_CREDENTIALS" to point to the Local Json Key File. 
I am using Java-8, 0.30 Version of the Jar.

com.google.api.gax.rpc.PermissionDeniedException: io.grpc.StatusRuntimeException: PERMISSION_DENIED: User not authorized to perform this action.

**Comment by cloudbetaguy** [comment]
access issues are resolved.

**Comment by justingrayston** [comment]
How did you resolve this? I have a similar problem
`io.grpc.StatusRuntimeException: PERMISSION_DENIED: Request had insufficient authentication scopes`

The service account that it should be using has PubSub admin credentials. What is odd, is that on an older binary of the connector i had this all working!!

I have the GOOGLE_APPLICATION_CREDENTIALS path set correctly, it is like the VM (in GCP) is not using the credentials provided.

**Comment by mdietz94** [comment]
If you have an error about scopes it's because the service account you are
using doesn't have permission to access PubSub APIs. It needs to either
have PubSub access or else entire project access. You  can read more at
https://developers.google.com/identity/protocols/googlescopes.

**Comment by justingrayston** [comment]
OK - doing it all in a single start.sh script worked. I guess the env variable was not scoped correctly.

**Comment by justingrayston** [comment]
@mdietz94 agreed, but what is odd is the VM service account, the default application details for gcloud had project editor rights, the service account I set up on the GOOGLE_APPLICATION_CREDENTIALS was PubSub admin. So I have no idea which account it was trying to use but didn't have scopes to access pubsub. Any how, got it working in the end. Thanks for the comment.
