### ISSUE TITLE
Do not hide Grpc Exceptions

### ISSUE THREAD

**Issue by lsenta** [GoogleCloudPlatform/pubsub#148]
I got a cryptic

```
Could not create publisher stub; no publishes can occur.
```

from: https://github.com/GoogleCloudPlatform/pubsub/blob/master/kafka-connector/src/main/java/com/google/pubsub/kafka/sink/CloudPubSubGRPCPublisher.java#L38

I just forgot the `GOOGLE_APPLICATION_CREDENTIALS` env variable, but the catch hides the reason of the exception.

Proposed Fix:
https://github.com/GoogleCloudPlatform/pubsub/pull/147/files

**Comment by kamalaboulhosn** [comment]
The changes in #152 addressed this.
