### ISSUE TITLE
Query related to Prerunning steps

### ISSUE THREAD

**Issue by shashidesai** [GoogleCloudPlatform/pubsub#155]
Steps done as per 
https://github.com/GoogleCloudPlatform/pubsub/tree/master/kafka-connector#pre-running-steps

* I am able to create a service account and get the private key, but if I goto "IAM" tab and service account, the new service account exists.

As per Step 2:
"Go to the "IAM" tab, find the service account you just created and click on the dropdown menu named "Role(s)". Under the "Pub/Sub" submenu, select "Pub/Sub Admin"

The second step does not map to the current workflow. So could someone please clarify what has to be done for Step 2 ? 
As I am not sure how to set permission for service accounts for "Pub/Sub" but I have my account set to "Pub/Sub Admin". Is that sufficient enough ?

**Comment by mdietz94** [comment]
Yes, Pub/Sub Admin is the same thing.

**Comment by shashidesai** [comment]
thanks @mdietz94
