### ISSUE TITLE
ALPN is not configured properly - error seen only for CloudPubSubSourceConnector

### ISSUE THREAD

**Issue by shashidesai** [GoogleCloudPlatform/pubsub#156]
Steps done:
* git clone 
* mvn package 
* Used the created jar in the kafka connect setup

Setup:
* Using confluent platform docker image of `kafka connect` - `FROM confluentinc/cp-kafka-connect:4.1.0`
* Intend to use `CloudPubSubSourceConnector`
* Using the `master` branch of the pubsub connector to generate the jar.

ALPN is not configured error showed up, I referenced the previous issues related to ALPN but those were related to Sink connectors and the resolution for that was to update the `netty-tcnative-boringssl-static`.

Any suggestions ?

**Error seen**:
`com.google.pubsub.kafka.source.CloudPubSubSourceConnector.verifySubscription(CloudPubSubSourceConnector.java:209)\n\tat com.google.pubsub.kafka.source.CloudPubSubSourceConnector.start(CloudPubSubSourceConnector.java:117)\n\tat org.apache.kafka.connect.runtime.WorkerConnector.doStart(WorkerConnector.java:111)\n\tat org.apache.kafka.connect.runtime.WorkerConnector.start(WorkerConnector.java:136)\n\tat org.apache.kafka.connect.runtime.WorkerConnector.transitionTo(WorkerConnector.java:195)\n\tat org.apache.kafka.connect.runtime.Worker.startConnector(Worker.java:208)\n\tat org.apache.kafka.connect.runtime.distributed.DistributedHerder.startConnector(DistributedHerder.java:899)\n\tat org.apache.kafka.connect.runtime.distributed.DistributedHerder.access$1300(DistributedHerder.java:109)\n\tat org.apache.kafka.connect.runtime.distributed.DistributedHerder$15.call(DistributedHerder.java:915)\n\tat org.apache.kafka.connect.runtime.distributed.DistributedHerder$15.call(DistributedHerder.java:911)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)\n\tat java.lang.Thread.run(Thread.java:745)\nCaused by: java.lang.IllegalArgumentException: ALPN is not configured properly. See https://github.com/grpc/grpc-java/blob/master/SECURITY.md#troubleshooting for more information.\n\tat io.grpc.netty.GrpcSslContexts.selectApplicationProtocolConfig(GrpcSslContexts.java:166)\n\tat io.grpc.netty.GrpcSslContexts.configure(GrpcSslContexts.java:136)\n\tat io.grpc.netty.GrpcSslContexts.configure(GrpcSslContexts.java:124)\n\tat io.grpc.netty.GrpcSslContexts.forClient(GrpcSslContexts.java:94)\n\tat io.grpc.netty.NettyChannelBuilder$NettyTransportFactory$DefaultNettyTransportCreationParamsFilterFactory.<init>(NettyChannelBuilder.java:546)\n\tat io.grpc.netty.NettyChannelBuilder$NettyTransportFactory$DefaultNettyTransportCreationParamsFilterFactory.<init>(NettyChannelBuilder.java:539)\n\tat io.grpc.netty.NettyChannelBuilder$NettyTransportFactory.<init>(NettyChannelBuilder.java:477)\n\tat io.grpc.netty.NettyChannelBuilder.buildTransportFactory(NettyChannelBuilder.java:325)\n\tat io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:362)\n\tat com.google.pubsub.kafka.common.ConnectorUtils.getChannel(ConnectorUtils.java:53)\n\tat com.google.pubsub.kafka.source.CloudPubSubSourceConnector.verifySubscription(CloudPubSubSourceConnector.java:200)\n\t... 13 more\nCaused by: java.lang.ClassNotFoundException: org/eclipse/jetty/alpn/ALPN\n\tat java.lang.Class.forName0(Native Method)\n\tat java.lang.Class.forName(Class.java:348)\n\tat io.grpc.netty.JettyTlsUtil.isJettyAlpnConfigured(JettyTlsUtil.java:64)\n\tat io.grpc.netty.GrpcSslContexts.selectApplicationProtocolConfig(GrpcSslContexts.java:153)\n\t... 23 more\n"`

**Comment by kamalaboulhosn** [comment]
For sink or source, updating netty-tcnative-boringssl-static is a good thing to do. This can also be caused by compiling the connector on a different architecture from the one it is run on.

**Comment by shashidesai** [comment]
Thanks for the response @kamalaboulhosn .

The current dependency setup for `netty-tcnative-boringssl-static` 
`    <dependency>
      <groupId>io.netty</groupId>
      <artifactId>netty-tcnative-boringssl-static</artifactId>
      <version>2.0.8.Final</version>
      <classifier>${os.detected.classifier}</classifier>
    </dependency>
`

I have generated the jar on OSX and using it on a debian based docker image. Do you think that's causing this error ? Will try adding jar generation into the dockerfile. 
But it will be an overhead to add the jar generation to the docker image (not that the image is built often for `kafka_connect`)

**Comment by kamalaboulhosn** [comment]
Yes, if you were generating the jar on OSX and then using it on a Debian-based docker image, then it is likely the cause of the issue. The netty library pulls in architecture-specific libraries that are not compatible across platforms.

**Comment by shashidesai** [comment]
@kamalaboulhosn - I generated the jar in the same docker image and I still see the same error. any suggestions ? 

`Caused by: java.lang.IllegalArgumentException: ALPN is not configured properly. See https://github.com/grpc/grpc-java/blob/master/SECURITY.md#troubleshooting for more information.
	at io.grpc.netty.GrpcSslContexts.selectApplicationProtocolConfig(GrpcSslContexts.java:166)
	at io.grpc.netty.GrpcSslContexts.configure(GrpcSslContexts.java:136)
	at io.grpc.netty.GrpcSslContexts.configure(GrpcSslContexts.java:124)
	at io.grpc.netty.GrpcSslContexts.forClient(GrpcSslContexts.java:94)
	at io.grpc.netty.NettyChannelBuilder$NettyTransportFactory$DefaultNettyTransportCreationParamsFilterFactory.<init>(NettyChannelBuilder.java:546)
	at io.grpc.netty.NettyChannelBuilder$NettyTransportFactory$DefaultNettyTransportCreationParamsFilterFactory.<init>(NettyChannelBuilder.java:539)
	at io.grpc.netty.NettyChannelBuilder$NettyTransportFactory.<init>(NettyChannelBuilder.java:477)
	at io.grpc.netty.NettyChannelBuilder.buildTransportFactory(NettyChannelBuilder.java:325)
	at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:362)
	at com.google.pubsub.kafka.common.ConnectorUtils.getChannel(ConnectorUtils.java:53)
	at com.google.pubsub.kafka.source.CloudPubSubSourceConnector.verifySubscription(CloudPubSubSourceConnector.java:200)
	... 13 more
Caused by: java.lang.ClassNotFoundException: org/eclipse/jetty/alpn/ALPN
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at io.grpc.netty.JettyTlsUtil.isJettyAlpnConfigured(JettyTlsUtil.java:64)
	at io.grpc.netty.GrpcSslContexts.selectApplicationProtocolConfig(GrpcSslContexts.java:153)
	... 23 more`

**Comment by shashidesai** [comment]
Thanks @kamalaboulhosn - the issue was resolved after having the jar generated inside the docker image.
