### ISSUE TITLE
How to wait for an ack message to be delivered?

### ISSUE THREAD

**Issue by j256** [GoogleCloudPlatform/pubsub#167]
It seems that the `AckReplyConsumer.ack()` and `nack()` messages are asynchronous.  Is there any mechanism for me to wait for the background messages to complete.  I'm looking for an equivalent to the `Publisher.publishAllOutstanding()` but for acknowledgements.

Thanks.

**Comment by kamalaboulhosn** [comment]
There is no way to wait for the ack or nack and it wouldn't necessarily make sense to do so. In general, these operations are best-effort and there are no guarantees that a message has been acked or nacked, even if these responses are sent. While it is not frequent that acks fail, it can still happen (resulting in duplicates) and the subscriber client will not have any way of knowing. 

In the future, I'd recommend submitting these types of questions to StackOverflow under the google-cloud-pubsub tag (https://stackoverflow.com/questions/tagged/google-cloud-pubsub). This repo doesn't really cover the client libraries for Cloud Pub/Sub; it is specific to the Kafka Connector and the load test framework.

**Comment by j256** [comment]
Thanks @kamalaboulhosn .  Noted.
