### ISSUE TITLE
Docs on resurface time for nacked messages in pub sub subscription queue

### ISSUE THREAD

**Issue by creativcoder** [GoogleCloudPlatform/pubsub#168]
Hi are there docs explaining about the (guarantees if any) on how long it takes for nacked messages to resurface back to the subscriber ?

**Comment by kamalaboulhosn** [comment]
There are no guarantees around how long nacked messages will take to be redelivered. When they are successfully nacked, they become available to be redelivered, but it may not happen immediately. Additionally, the underlying request used to nack ([modifyAckDeadline](https://cloud.google.com/pubsub/docs/reference/rpc/google.pubsub.v1#google.pubsub.v1.ModifyAckDeadlineRequest)) is best effort (though it should fail only rarely) and so it is possible that calling nack will not result in the message getting nacked immediately, which means it could end up waiting for the original ack deadline.

In the future, I'd recommend submitting these types of questions to[ StackOverflow under the google-cloud-pubsub tag](https://stackoverflow.com/questions/tagged/google-cloud-pubsub). This repo doesn't really cover the general Cloud Pub/Sub service or clients; it is specific to the Kafka Connector and the load test framework.
