### ISSUE TITLE
Please add release tags or versions

### ISSUE THREAD

**Issue by daithi-walker** [GoogleCloudPlatform/pubsub#176]
While working with Google on issues relating to this connector, we are unable to advise what version of this connector we are using, only that we compiled the jar on date x.

Would it be possible to add a release version or some kind of tag to this going forward?

**Comment by kamalaboulhosn** [comment]
I agree, this is a great idea. I have created a release and also added instructions to build the connector from the release. As we make future changes, I will ensure that we continue to create releases.
