### ISSUE TITLE
Pub Sub messages failed due to due to DEADLINE_EXCEEDED:

### ISSUE THREAD

**Issue by ayushj158** [GoogleCloudPlatform/pubsub#184]
Hello 

We are publishing some bulk messages to pub sub and intermittently we keep seeing few messages getting failed due to : 

io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED:  . 
grpc-default-worker-ELG-2-2]` 7267 --- INFO  i.g.n.s.i.n.h.c.h.DefaultHttp2ConnectionDecoder  - [id: 0x204dac20, L:/10.8.61.36:58898 - R:pubsub.googleapis.com/172.217.20.74:443] ignoring HEADERS frame for stream RST_STREAM sent. {}

I checked one the previous open issues https://github.com/googleapis/google-cloud-java/issues/2722 which states the issues is resolved. I am not sure what is the resolution ? 

- just upgrading to the higher versions will fix the issue or 
- we need to add some custom timeout settings (if yes where , RetrySettings?)
@pongad @kir-titievsky

**Comment by kamalaboulhosn** [comment]
Is this pertaining to the Kafka Connector or to using the Java client library directly? If the latter, please enter an issue in the [google-cloud-java ](https://github.com/googleapis/google-cloud-java/)repository where that code lives. Thanks!

**Comment by ayushj158** [comment]
> Is this pertaining to the Kafka Connector or to using the Java client library directly? If the latter, please enter an issue in the [google-cloud-java ](https://github.com/googleapis/google-cloud-java/)repository where that code lives. Thanks!

@kamalaboulhosn Thanks for pointing me to right direction, it is indeed for java library ! Closing the issue here.
