### ISSUE TITLE
What is the Function to Push Google Pub/Sub data to BigQuery?

### ISSUE THREAD

**Issue by abinpbiju** [GoogleCloudPlatform/pubsub#189]
What is the Function to Push Google Pub/Sub data to BigQuery?

**Comment by kamalaboulhosn** [comment]
There is no direct way to get data from Google Cloud Pub/Sub into BigQuery. One generally writes a subscriber to do this or uses [Cloud Dataflow](https://cloud.google.com/dataflow/)
