### ISSUE TITLE
Publish Pre-Built JARs

### ISSUE THREAD

**Issue by elithrar** [GoogleCloudPlatform/pubsub#191]
Publishing the pre-built JARs (i.e. via Travis CI, or otherwise) would allow users to copy the JAR - e.g. into a Docker image - without having to clone + build the package themselves with a Java toolchain.

**Comment by antonmry** [comment]
This feature would be very handy for us, I guess it should be quite easy with Github actions deployed it to Releases instead of tags.

Also, the last tag is from April but there are interesting things in master. It would be great to have a v0.4 release with the new commits.
