### ISSUE TITLE
PubSub messages expire cyclically 

### ISSUE THREAD

**Issue by christian-roggia** [GoogleCloudPlatform/pubsub#207]
We have in our infrastructure a very basic Pub/Sub setup that is configured in the following way:
- Subscription
- - Acknowledgement deadline: 300s
- - Message retention duration: 1d
- - Delivery type: Pull

We publish around 15.000 messages per day, each message requires between 5 to 15 seconds to be processed by the subscriber process. The messages are extremely small (less than 10kb).

We set the Golang `subscription.ReceiveSettings.MaxOutstandingMessages` to `1` as we want to process the messages sequentially in our development environment.

The receive function written in Golang is simplified in the following way:
```
function (...) {
  timer.start()
  ...
  // Process the message
  ...
  timer.stop()
  msg.Ack()
}
```

The timer is logged and shows us that the work requires between 5 and 15 seconds, once the job is finished the message is acknowledged.

The issue we are currently facing is that, even if the message processing is supposed to be sequential and even if the ACK deadline is set to 5 minutes and the max extension period to 10 minutes (default value) the messages eventually will expire in a cyclical way.

We have observed the following behaviour in Stackdriver:
![img 1](https://user-images.githubusercontent.com/6957360/63021171-49942080-bea0-11e9-90f2-3523a82d2ae2.png)
![img 2](https://user-images.githubusercontent.com/6957360/63021176-4ef16b00-bea0-11e9-8bb8-a985556ec976.png)

After hours of debugging we couldn't find a single reason why cyclically there is a spike in expired requests.

**Comment by kamalaboulhosn** [comment]
This repo deals specifically with the load test framework and the Kafka Connector. For help with the Go client, please enter your issue in the G[o GitHub repo](http://github.com/GoogleCloudPlatform/google-cloud-go).
