### ISSUE TITLE
Security Violation : SonaType violations received due to siddhi-io-googlepubsub dependency

### ISSUE THREAD

**Issue by siddharthsbhadauria** [GoogleCloudPlatform/pubsub#218]
While building the connector and running SonaType IQ scan reports multiple security vulnerabilities due to org.wso2.extension.siddhi.io.googlepubsub:siddhi-io-googlepubsub.
We tried multiple scenarios and this depency is only pulled when we use these 3 dependencies together : 
- com.google.cloud:google-cloud-pubsub
- com.google.apis:google-api-services-pubsub.
- io.grpc:grpc-all
- org.mockito:mockito-core

This is an urgent issue and a security blocker for us.
Appreciate any help.

**Comment by kamalaboulhosn** [comment]
The org.wso2.extension.siddhi.io.googlepubsub:siddhi-io-googlepubsub is not a library used anywhere by the Pub/Sub connector. It looks like it a [library owned by someone else](https://github.com/siddhi-io/siddhi-io-googlepubsub). I think you may need to talk to them about the vulnerabilities.

**Comment by haris-aryan** [comment]
Hi Kamal, Thanks for your quick response. Yes this exactly was the reason why we scanned this application more than 20 times  and each time vulenrabilites were reported beung originated from org.wso2.extension.siddhi.io.googlepubsub:siddhi-io-googlepubsub. 
We check dependency tree, scanned verbose build logs but didn't find this dependency but each time we run Nexus IQ Sonatype Scan - we get this dependency.  

[cps_connector_nexus_iq_scan_report_12-May.pdf](https://github.com/GoogleCloudPlatform/pubsub/files/4614256/cps_connector_nexus_iq_scan_report_12-May.pdf)
I am attaching the report for your reference.

**Comment by kamalaboulhosn** [comment]
Thank you, the report was helpful. It looks like the scanning tool couldn't figure out which package was involved, so it guessed, which is why it points to org.wso2.extension.siddhi.io.googlepubsub:siddhi-io-googlepubsub. I have entered #220 to update dependencies.

**Comment by haris-aryan** [comment]
Thanks Kamal.. This is very quick. Have run the report again and all vulnerabilities are gone :)
