### ISSUE TITLE
NPE for "null" messages on kafka topics

### ISSUE THREAD

**Issue by vladgusev** [GoogleCloudPlatform/pubsub#219]
Under certain conditions (using Debezium with SQL Server + Kafka to PubSub Sink), it's possible to generate a "null" message that causes NPE and shutdown of connector. 

Below is a snippet of the exception:

```
RROR WorkerSinkTask{id=CPSSinkConnector-4} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted. Error: null (org.apache.kafka.connect.runtime.WorkerSinkTask)

java.lang.NullPointerException
	at com.google.protobuf.ByteString.copyFromUtf8(ByteString.java:400)
	at com.google.pubsub.kafka.sink.CloudPubSubSinkTask.handleValue(CloudPubSubSinkTask.java:232)
	at com.google.pubsub.kafka.sink.CloudPubSubSinkTask.put(CloudPubSubSinkTask.ja
```
```

**Comment by ls12styler** [comment]
Just wondering, is the NULL message a tombstone message on a compacted Kafka Topic? If so, it could be worth having a Single Message Transform to discard the NULL value.

**Comment by kamalaboulhosn** [comment]
What is the desired result with the null message? Is it that it should be dropped or sent through to Cloud Pub/Sub?

**Comment by vladgusev** [comment]
I tested it by "return ByteString.copyFromUtf8(str);" in case of a null string and that kept the connector from crashing.  From there, handled in DF job on consumption from pub/sub topic.
