### ISSUE TITLE
Kafka Connector with Pub/Sub Lite

### ISSUE THREAD

**Issue by antonmry** [GoogleCloudPlatform/pubsub#228]
Does the Kafka Connector support Pub/Sub Lite? https://cloud.google.com/pubsub/lite/docs . It seems the SDK is different from the Pub/Sub one so I guess it isn't. If it's the case, is in the roadmap to add support for it?

**Comment by kamalaboulhosn** [comment]
It does not currently support Pub/Sub Lite, no. It is something we would consider based on user feedback, though there are no concrete plans at this time. We will keep this open as a feature request.
