### ISSUE TITLE
Message compression while publishing to GCP P/S

### ISSUE THREAD

**Issue by udaedrewip** [GoogleCloudPlatform/pubsub#229]
Hi , 
Is there feature available in sink connector to compress the message before publishing to Pub-sub  as Pubsub has max msg limit of 10 MB and we want to compress the messages before sending to overcome this.

**Comment by kamalaboulhosn** [comment]
This feature is not currently supported, no. I'm not sure it necessarily belongs within the connector, either. If the connector compressed the messages, it means that the Cloud Pub/Sub subscriber that ultimately receives the message would have to be aware of the compression scheme used by the connector so it could decompress the messages. 

Instead, the best option would be for you to implement a custom [Converter](https://kafka.apache.org/20/javadoc/org/apache/kafka/connect/storage/Converter.html) that takes the `value` specified in `toConnectData​`, compresses it, and returns a `SchemaAndValue` object with the compressed data as the value and `BYTES_SCHEMA` as the schema. You would then [configure the `value.converter`](https://docs.confluent.io/current/connect/userguide.html#configuring-key-and-value-converters) to use this compressing converter.
