### ISSUE TITLE
Query : Performance issues while using ordering key in CPS connector

### ISSUE THREAD

**Issue by siddharthsbhadauria** [GoogleCloudPlatform/pubsub#249]
Hi Guys,

We are experiencing a huge drop in the throughput when using orderingKeySource : Partition in the sink connector.

PFB Stats :
> Kafka Connect worker count : 3 (Distributed Mode).
> Max.tasks : 5.
> orderingKeySource : Partition

Kafka Topic partition count       |      Throughout without ordering       |    Throughput with ordering 
                     1                           |           3533.33 messages/second       |       127.31 messages/second
                     10                         |           5555.55 messages/second       |       1041.66 messages/second
                     20                         |           8333.33 messages/second       |       1754.38 messages/second

We are using the same kafka topic and the same google project for every test,
Can you please suggest what could be the cause of the performance drop and suggest a possible solution to this.

Regards,
Siddharth

**Comment by kamalaboulhosn** [comment]
Throughput is going to be limited if using partition as the ordering key. Ordering in Cloud Pub/Sub works best when there is a very diverse number of keys, on the order of thousands. Ordering using the partition is only going to work for low-throughput topics or topics with a lot of partitions. I have put in #250 to fix the documentation to reflect this fact.
