### ISSUE TITLE
Question about cloud-pubsub-jms

### ISSUE THREAD

**Issue by oliverhenlich** [GoogleCloudPlatform/pubsub#254]
Hi,

Apologies if this is not the correct place to ask this question. I'm just not sure where else to ask.

It looks like a number of years ago there was a project to implement a Java JMS provider backed by PubSub here: https://github.com/GoogleCloudPlatform/pubsub/projects/1

It looks like this effort has been abandoned and the code for it deleted. 
Do you know if this effort has been moved somewhere else?
Are there any plans or roadmap items about providing a JMS provider?

Cheers
Oliver

**Comment by kamalaboulhosn** [comment]
There was a project some time ago and indeed the effort has been abandoned. It has not been moved as there were no developers who were supporting the effort. If this is a feature you would like added, I would recommend adding a feature request in the [public Cloud Pub/Sub issue tracker](https://issuetracker.google.com/issues?q=componentid:187173).
