### ISSUE TITLE
External IP

### ISSUE THREAD

**Issue by Ryner51** [GoogleCloudPlatform/pubsub#258]
Our company policy has restricted the use of external ips within GCP. When trying to run the load test for pub / sub I am getting the following error:

`{"code":"CONDITION_NOT_MET","message":"Instance 'cps-loadtest-cps-gcloud-java-publisher-16-3mpv' creation failed: Constraint constraints/compute.vmExternalIpAccess violated for project`

Is there anyway to tell the load test not to use an external ip or is this a requirement in order to run the test?

**Comment by dpcollins-google** [comment]
Not currently. The vm needs to expose access to wherever the driver is running to send stats. You could modify the vm template [here](https://github.com/GoogleCloudPlatform/pubsub/blob/b7c9dd625f8af9150c63eb4e83b7940807f89ec6/load-test-framework/src/main/java/com/google/pubsub/flic/controllers/resource_controllers/GCEComputeResourceController.java#L162)  to conform with this constraint, and then run the driver program itself on a gce vm within an isolated network

**Comment by dpcollins-google** [comment]
Closing
