### ISSUE TITLE
Request: provide a standalone Docker version (including Kafka) 

### ISSUE THREAD

**Issue by informatica92** [GoogleCloudPlatform/pubsub#270]
Hi all, 
I started to use this connector many months ago and it woks very nice actually. The only problem I see is that it is not so easy to install and configure. 
So I started to think that probably it would be nice to have a containerized version of the connector (including also kafka) so that each deploy would be much much easier.

What do you think about this?

**Comment by dpcollins-google** [comment]
Hello Marco,

Thank you for reaching out. The overall intent of this connector is to provide an easy way for users who already have Kafka setups to interact with Cloud Pub/Sub and move their data between the two systems. If you don't already have a Kafka instance running to copy data to/from, why do you want to use this connector?

Thanks,

Daniel

**Comment by dpcollins-google** [comment]
Closing
