### ISSUE TITLE
netty dependency is too old to compile on aarch64

### ISSUE THREAD

**Issue by fingon** [GoogleCloudPlatform/pubsub#301]
netty fixed it somewhere between 2.0.32 and 2.0.36 (2.0.36 works at least)

https://github.com/GoogleCloudPlatform/pubsub/blob/c8c0fc415c9a2ecf4b9542dae8416407001e659f/kafka-connector/pom.xml#L30

**Comment by samarthsingal** [comment]
Cut release https://github.com/GoogleCloudPlatform/pubsub/releases/tag/v0.11-alpha that should bump the dependency.
