### ISSUE TITLE
TopicAdminClient UnauthenticatedException When Settings Endpoints

### ISSUE THREAD

**Issue by benshriki** [GoogleCloudPlatform/pubsub#333]
Hi,
I've found an issue when settings TopicAdminClient with endpoint.

**Current behavior:** 
- When i try to set TopicAdminClient  with credentials out of a json(String) and endpoint different then the global "pubsub.googleapis.com" end point i get an UnauthenticatedException. 
- When i use ADC authentication and set the environment variable GOOGLE_APPLICATION_CREDENTIALS to point to a json file with the same content i can set to all endpoints with no errors.
- When i try to set TopicAdminClient  with credentials out of a json(String) and use the global endpoint pubsub.googleapis.com" i get no errors.

**Expected behavior:** 
To be able to use both authentication ways and set any endpoint without encountering any error. 

**Example:**
```
...
ServiceAccountCredentials cred = ServiceAccountCredentials
              .fromStream(new ByteArrayInputStream(jsonCredentials.getBytes()));  // json as String

CredentialsProvider credentialsProvider = FixedCredentialsProvider.create(cred); 

TopicAdminSettings topicAdminSettings = TopicAdminSettings.newBuilder()
                                 .setCredentialsProvider(credentialsProvider)   // credentials out of given json file
                                 .setEndpoint(endpoint)                         // endpoint different then global endpoint
                                 .build();

TopicAdminClient topicAdminClient = TopicAdminClient.create(topicAdminSettings);

topicAdminClient.getTopic(someTopic);
```

the code above produce the following exception:
`com.google.api.gax.rpc.UnauthenticatedException: io.grpc.StatusRuntimeException: UNAUTHENTICATED: Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.'`

**Comment by kamalaboulhosn** [comment]
This issue should be in the Java library repo, so I have created it there: https://github.com/googleapis/java-pubsub/issues/1480.
