### ISSUE TITLE
getStats() throws UnsupportedOperationException

### ISSUE THREAD

**Issue by Yanson** [GoogleCloudPlatform/pubsub#41]
These stats are very important. Please implement!

```java
  public PublisherStats getStats() {
    // TODO: Implement this.
    throw new UnsupportedOperationException();
  }
```

https://github.com/GoogleCloudPlatform/pubsub/blob/master/client/src/main/java/com/google/cloud/pubsub/PublisherImpl.java#L149

**Comment by davidtorres** [comment]
Hi Yanson,

Thanks for your interest in the library, we understand statistics are important to you, but at this point we can't promise any due date to implement them.

Said that, may I ask you what specific stats would you expect from the library and from the publisher and subscriber classes.

Thanks,

- David

**Comment by Yanson** [comment]
Since I don't know the specifics of the library internals, it's hard to say.

However, those in the API are definitely a good start. Adding pending bytes (i.e. queue size in bytes) would also be nice, as well as num retries, perhaps.

**Comment by mdietz94** [comment]
Closing since this client library is migrating to google-cloud-java.
