### ISSUE TITLE
Flic errors out when running in Kafka-only mode

### ISSUE THREAD

**Issue by kir-titievsky** [GoogleCloudPlatform/pubsub#44]
$python run.py --project=google.com:kir-learns-cloud --broker=10.142.0.7
Result:
Invalid --client_type parameter given. Must be a comma deliminated sequence of client types. Allowed client types are 'gcloud_python', 'gcloud_ja
va', 'vtk', and 'experimental'. (gcloud) was provided. Kafka is assumed if --broker is provided.

The code did not actually run. Just exited.  Expected: the code runs against Kafka.

**Comment by mdietz94** [comment]
Fixed.
