### ISSUE TITLE
What to do with experimental client?

### ISSUE THREAD

**Issue by pongad** [GoogleCloudPlatform/pubsub#54]
When merging the experimental client into google-cloud-java, I fixed [a](https://github.com/GoogleCloudPlatform/google-cloud-java/pull/1554) [number](https://github.com/GoogleCloudPlatform/google-cloud-java/pull/1558) [of](https://github.com/GoogleCloudPlatform/google-cloud-java/pull/1560) [race](https://github.com/GoogleCloudPlatform/google-cloud-java/pull/1581) [conditions](https://github.com/GoogleCloudPlatform/google-cloud-java/pull/1586) that often deadlocks on Travis.

Should be port these fixes back to experimental client? Or set the experimental client to be the same at the google-cloud-java client, then change it later as we want to experiment more? Something else?

**Comment by davidtorres** [comment]
IMO, we should replace the experimental code with the latest in  google-cloud-java, with the difference of enabling streaming pull.

**Comment by mdietz94** [comment]
I agree
