### ISSUE TITLE
Complete JMS Publisher test suite 

### ISSUE THREAD

**Issue by kir-titievsky** [GoogleCloudPlatform/pubsub#56]
The plan is to 
1. Take section 6 in  [1]
2. port them over to Cloud Pub/Sub 
3. Add tests for multiple subscription pattern, if applicable.

[1] https://github.com/skyscreamer/nevado/wiki/Master-Feature-Grid

**Comment by urshunkeler** [comment]
The Publisher test suite (this issue) is being implemented in the branch "jms_publisher_test_suite". The tests currently fail because of the following issues:
- #65 
- #66 
- #67 
- #68 
- #69 
- #70

**Comment by urshunkeler** [comment]
The tests are now complete (with respect to the Nevado tests in section 6), they compile, but they do not fully work. This means that when a test fails, it might also be because the test is not properly implemented (see the TODOs in the source code).
