### ISSUE TITLE
Implement PubSubTopic class

### ISSUE THREAD

**Issue by urshunkeler** [GoogleCloudPlatform/pubsub#66]
The Publisher test suite (bug #56) is being implemented in the branch "jms_publisher_test_suite". The tests currently fail because the PubSubTopic class is not implemented.

**Comment by kir-titievsky** [comment]
Frank, assigning this to you for now. Let me know if this makes sense as the first point. Urs thanks for opening.

**Comment by XiaoYang-Code4Fun** [comment]
The PubSubTopic class has already been implemented as PubSubTopicDestination in com.google.pubsub.jms.light.destination.

Replacing the PubSubTopic class with PubSubTopicDestination class in test.
