### ISSUE TITLE
Implement MessageConsumer interface

### ISSUE THREAD

**Issue by ujraaja** [GoogleCloudPlatform/pubsub#71]

**Comment by kir-titievsky** [comment]
Raaja, when you can, could you please specify which interface classes you are taking on?  There are several in the consumer interface.

**Comment by ujraaja** [comment]
Implementing javax.jms.MessageConsumer interface and hooking up com.google.cloud.pubsub.spi.v1.Subscriber as the message source for the consumer.

**Comment by ujraaja** [comment]
The task is a duplicate of #65
