### ISSUE TITLE
Decide on testing approach: mocking vs. not and how to deal with unimplemented.

### ISSUE THREAD

**Issue by kir-titievsky** [GoogleCloudPlatform/pubsub#72]
From Urs: I ported the tests from the Nevado project for section 6 (steps 1 and 2 of issue #56).

What is working:
- All tests ported
- Tests compile
- Tests run
What needs to be done:
- Tests are not fully functional. Some of the Nevado tests are specific to their code, and these tests need to be adapted to our code (I noted this as a TODO in the source code)
- The start and stop test methods need to be implemented (to set up and close a default connection). Should be pretty straight forward except for the next point.
- Need to set up a PubSub connection. Possibilities:
- We can easily take the test environment from the integration test (but it depends on deprecated code).
- We can use the Google Cloud PubSub emulator, but I have not yet found an easy way to run it without installing the - Google Cloud tool chain (so will not work in travis)
We can use our access to the official Google Cloud PubSub server (but we should not share access on github, thus no travis)

We can mock the PubSub connection
For the PubSub connection, I would like to implement all possibilities and make it configurable. We can then decide whether for travis we run the deprecated emulator or use mocking (or do both in sequence).

Initial discussion indicate that all are leaning towards mocking.

**Comment by kir-titievsky** [comment]
In standup today, Maksym said he had some thoughts on this and would reach out to Urs directly.

**Comment by MMMarcy** [comment]
Adding little to the conversation, but as of version 0.11.1-alpha of google-cloud library, the *deprecated* package has been removed. 

We cannot reuse the environment from the integration test anymore as is.

**Comment by kir-titievsky** [comment]
@urshunkeler : Marcello is blocked on the decision here.  Any thoughts?

**Comment by urshunkeler** [comment]
I am in favor of mocking for automated tests. I am oncall this week, so I
cannot promise any progress.
